# Cloud Run service configuration for frontend
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: sales-order-frontend
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/execution-environment: gen2
spec:
  template:
    metadata:
      annotations:
        # Resource allocation
        run.googleapis.com/cpu: "1"
        run.googleapis.com/memory: "1Gi"
        
        # Scaling configuration
        autoscaling.knative.dev/minScale: "0"
        autoscaling.knative.dev/maxScale: "5"
        run.googleapis.com/execution-environment: gen2
    spec:
      serviceAccountName: sales-order-frontend-sa@PROJECT_ID.iam.gserviceaccount.com
      containerConcurrency: 1000
      timeoutSeconds: 60
      containers:
      - image: gcr.io/PROJECT_ID/sales-order-frontend:latest
        ports:
        - name: http1
          containerPort: 8080
        env:
        - name: ENVIRONMENT
          value: "production"
        - name: BACKEND_URL
          value: "https://sales-order-backend-uc.a.run.app"
        resources:
          limits:
            cpu: "1000m"
            memory: "1Gi"
          requests:
            cpu: "100m"
            memory: "256Mi"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 60
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
  traffic:
  - percent: 100
    latestRevision: true